name: Sync Fork from Upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/AGH-team-Red/landing-page.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Merge Upstream/main into your fork's main branch
        run: |
          git checkout main
          git merge upstream/main --no-ff --no-edit

      - name: Push Changes to Fork
        run: |
          git push origin main
