name: Sync From Upstream and Deploy to Vercel

on:
  repository_dispatch:
    types: [sync-from-upstream-and-deploy]
  workflow_dispatch:

jobs:
  sync_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: Add Upstream Remote (Original Org Repo)
        run: |
          git remote add upstream https://github.com/AGH-team-Red/landing-page.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Merge Upstream/main into fork's main branch
        run: |
          git checkout main
          git merge upstream/main --no-ff --no-edit

      - name: Remove upstream-specific trigger workflow from fork
        run: |
          if [ -f ".github/workflows/trigger-fork-sync.yml" ]; then
            echo "Found upstream trigger workflow. Removing it..."
            git rm .github/workflows/trigger-fork-sync.yml
            # Only commit if there are staged changes (i.e., git rm did something)
            # and to avoid errors if the commit is empty.
            if ! git diff --staged --quiet; then
              git commit -m "Sync from upstream and remove upstream-specific trigger workflow"
            else
              echo "No changes to commit after attempting to remove workflow file."
            fi
          else
            echo "Upstream trigger workflow not found, no removal needed."
          fi

      - name: Push Changes to Fork
        run: |
          git push origin main

      - name: Trigger Vercel Deployment
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
