name: Trigger Fork Sync and Deploy

on:
  push:
    branches:
      - main

jobs:
  trigger_fork_action:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository_dispatch on fork
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.FORK_SYNC_PAT }}
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: 'CALLmeDOMIN',
              repo: 'quelldata',
              event_type: 'sync-from-upstream-and-deploy',
              client_payload: {
                sha: context.sha,
                ref: context.ref
              }
            });
            console.log('Successfully triggered sync-from-upstream-and-deploy event on fork.');
